/* This file is automatically generated by NRPy+. Do not edit. */

/* EVOLVED VARIABLES: */
#define NUM_EVOL_GFS 26
#define ADD00GF	0
#define ADD01GF	1
#define ADD02GF	2
#define ADD11GF	3
#define ADD12GF	4
#define ADD22GF	5
#define ALPHAGF	6
#define BETU0GF	7
#define BETU1GF	8
#define BETU2GF	9
#define CFGF	10
#define HDD00GF	11
#define HDD01GF	12
#define HDD02GF	13
#define HDD11GF	14
#define HDD12GF	15
#define HDD22GF	16
#define LAMBDAU0GF	17
#define LAMBDAU1GF	18
#define LAMBDAU2GF	19
#define TRKGF	20
#define UUGF	21
#define VETU0GF	22
#define VETU1GF	23
#define VETU2GF	24
#define VVGF	25


 /* AUXILIARY VARIABLES: */
#define NUM_AUX_GFS 1
#define HGF	0


/* PARITY TYPES FOR EVOLVED VARIABLES.
   SEE "Tutorial-Start_to_Finish-BSSNCurvilinear-Two_BHs_Collide.ipynb" FOR DEFINITIONS. */
const int8_t evol_gf_parity[26] = { 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 0, 4, 5, 6, 7, 8, 9, 1, 2, 3, 0, 0, 1, 2, 3, 0 };
